# Generated by Django 4.1.1 on 2022-09-22 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclosacademicos',
            options={'ordering': ['anno', 'ciclo'], 'verbose_name': 'CiclosAcademico'},
        ),
        migrations.AlterModelOptions(
            name='cursos',
            options={'ordering': ['curso', 'codigo'], 'verbose_name': 'Curso'},
        ),
        migrations.AlterModelOptions(
            name='docentes',
            options={'ordering': ['apellido_p', 'apellido_m', 'nombres'], 'verbose_name': 'Docente'},
        ),
    ]
