# Generated by Django 4.1.1 on 2022-09-22 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_ciclosacademicos_options_alter_cursos_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='apellido_m',
            field=models.CharField(max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='apellido_p',
            field=models.CharField(max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='codigo_uni',
            field=models.CharField(max_length=9, verbose_name='Código UNI'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombres',
            field=models.CharField(max_length=40, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='numero_dni',
            field=models.CharField(max_length=9, verbose_name='Número de DNI'),
        ),
        migrations.AlterField(
            model_name='ciclosacademicos',
            name='anno',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='ciclosacademicos',
            name='ciclo',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='Ciclo'),
        ),
        migrations.AlterField(
            model_name='ciclosacademicos',
            name='tipo',
            field=models.CharField(choices=[('N', 'Normal'), ('V', 'Vacacional')], max_length=1, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='codigo',
            field=models.CharField(max_length=5, verbose_name='Código del Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='curso',
            field=models.CharField(max_length=40, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='sistema_evaluacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academico.sistemaevaluacion', verbose_name='Sist. de Evaluación'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='apellido_m',
            field=models.CharField(max_length=20, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='apellido_p',
            field=models.CharField(max_length=20, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='nombres',
            field=models.CharField(max_length=40, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='docentes',
            name='nro_dni',
            field=models.CharField(max_length=9, verbose_name='Número de DNI'),
        ),
        migrations.AlterField(
            model_name='sistemaevaluacion',
            name='sistema_evaluacion',
            field=models.CharField(max_length=1, verbose_name='Sist. de Evaluación'),
        ),
    ]
